/**
 * The two documentation surfaces, read off disk.
 *
 * `/developer-docs` is generated by a forked jsdoc template and `/api-docs` is
 * Swagger UI with a stylesheet bolted on. Neither is compiled, neither is
 * rendered by any other test, and both are built from sources that can drift
 * apart without anything failing. This is what notices.
 *
 * Three things it is really guarding, each of which was a defect in #140:
 *
 * - **The front page images 404.** The README references them relative to the
 *   repository root, which is wrong once jsdoc emits the same markup into
 *   `docs/developer/`. That was broken on every build for months and looks like
 *   nothing at all in a diff.
 * - **The palette is a copy.** `marp-docs.css` and `swagger.css` each restate
 *   the colours from `tokens.css`, because a built file has to work opened from
 *   disk. A copy drifts; this is the thing that says so.
 * - **The fork is supposed to be a diff.** `docs/developer-theme/` is docdash
 *   2.0.2 with two files changed. If the rest of it starts changing, the next
 *   docdash upgrade stops being a comparison and becomes an excavation.
 *
 * No server, no browser, no database.
 *
 * @fileoverview Fast-tier checks on the developer docs theme and the Swagger theme.
 * @author Isaac Travers
 * @module tests/docs-branding
 */

const fs = require('fs');
const path = require('path');

/** Repository root, so every path below reads the same from any directory. */
const ROOT = path.join(__dirname, '..');

/** The forked template, and the upstream it was forked from. */
const THEME = path.join(ROOT, 'docs', 'developer-theme');
const UPSTREAM = path.join(ROOT, 'node_modules', 'docdash');

/** The generated site. Committed, so it is as much a source as the theme is. */
const BUILT = path.join(ROOT, 'docs', 'developer');

/**
 * Reads a file as text, with a failure message naming it.
 *
 * @param {...string} parts path segments joined from the repository root.
 * @returns {string} the file contents.
 */
function read(...parts) {
    const file = path.join(...parts);

    if (!fs.existsSync(file)) {
        throw new Error(`missing: ${path.relative(ROOT, file)}`);
    }

    return fs.readFileSync(file, 'utf8');
}

/**
 * Every custom property declared in the first `:root { ... }` block of a
 * stylesheet.
 *
 * Only the first block, deliberately. The palette is declared once at the top of
 * each file and the rule these tests enforce is that nothing below it declares a
 * colour, so a second `:root` further down would be the failure rather than
 * something to merge in.
 *
 * @param {string} css the stylesheet text.
 * @returns {Object<string,string>} property name to value, both trimmed.
 */
function rootTokens(css) {
    const block = css.match(/:root\s*\{([\s\S]*?)\}/);

    if (!block) {
        return {};
    }

    const tokens = {};

    for (const line of block[1].split('\n')) {
        const declaration = line.match(/^\s*(--[\w-]+)\s*:\s*(.+?);\s*$/);

        if (declaration) {
            tokens[declaration[1]] = declaration[2].trim();
        }
    }

    return tokens;
}

/**
 * Lists every file under a directory, as paths relative to it.
 *
 * @param {string} directory absolute directory to walk.
 * @returns {string[]} relative paths with forward slashes, sorted.
 */
function filesUnder(directory) {
    const found = [];

    const walk = (current) => {
        for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
            const full = path.join(current, entry.name);

            if (entry.isDirectory()) {
                walk(full);
                continue;
            }

            found.push(path.relative(directory, full).split(path.sep).join('/'));
        }
    };

    walk(directory);

    return found.sort();
}

/**
 * Line endings, removed before anything is compared.
 *
 * The fork is tracked and `node_modules/docdash` is not, so on Windows git hands back
 * the fork with CRLF while npm leaves upstream at LF. Comparing bytes then reports every
 * one of the 27 unchanged files as drifted, on a checkout where nothing has drifted at
 * all -- and it passes in CI, which is Linux, so the suite is green in the one place
 * nobody is reading it. That is how this shipped. `lib.mjs` in the umbrella had already
 * learned it: *"Line endings differ across these repositories; comparing them is never
 * the point."*
 *
 * @param {string} value the text to normalise.
 * @returns {string} the same text with CRLF collapsed and trailing whitespace dropped.
 */
const normalise = (value) => value.split('\r\n').join('\n').trimEnd();

/**
 * A file's contents, with its line endings normalised.
 *
 * @param {string} file absolute path.
 * @returns {string} the normalised text.
 */
const text = (file) => normalise(fs.readFileSync(file, 'utf8'));

/** The MARP theme for the generated site. */
const marpDocsCss = read(THEME, 'static', 'styles', 'marp-docs.css');

/** The MARP theme for Swagger UI. */
const swaggerCss = read(ROOT, 'swagger.css');

/** The palette every MARP surface is supposed to share. */
const tokensCss = read(ROOT, 'frontend', 'shared', 'assets', 'css', 'tokens.css');

/** The forked layout, and the script that builds the same bar for Swagger. */
const layoutTmpl = read(THEME, 'tmpl', 'layout.tmpl');
const swaggerChrome = read(ROOT, 'swagger-chrome.js');

/** The front page of the built site. */
const builtIndex = read(BUILT, 'index.html');

describe('the palette is copied, not invented', () => {

    /**
     * The two stylesheets that carry a copy of the palette, and the properties
     * each is allowed to declare that `tokens.css` does not have. Both entries
     * are local and neither is a colour tokens.css could hold -- `--scrim` is
     * navy-1000 at an alpha, which CSS cannot derive from a hex property.
     */
    const COPIES = {
        'docs/developer-theme/static/styles/marp-docs.css': marpDocsCss,
        'swagger.css': swaggerCss,
    };

    /** Declared locally on purpose, and exempt from the comparison. */
    const LOCAL = ['--bar-height', '--mono-font', '--scrim'];

    const shared = rootTokens(tokensCss);

    test.each(Object.keys(COPIES))('%s declares nothing tokens.css does not have', (name) => {
        const mine = rootTokens(COPIES[name]);
        const unknown = Object.keys(mine)
            .filter((key) => !LOCAL.includes(key))
            .filter((key) => !(key in shared));

        expect(unknown).toEqual([]);
    });

    test.each(Object.keys(COPIES))('%s matches tokens.css value for value', (name) => {
        const mine = rootTokens(COPIES[name]);
        const drifted = Object.entries(mine)
            .filter(([key]) => key in shared)
            .filter(([key, value]) => value !== shared[key])
            .map(([key, value]) => `${key}: ${value} (tokens.css says ${shared[key]})`);

        expect(drifted).toEqual([]);
    });

    /**
     * The check above can only see the `:root` block, so a colour typed into a
     * rule is invisible to it. This is what makes the first check mean anything.
     */
    test.each(Object.keys(COPIES))('%s states no colour below its palette', (name) => {
        const css = COPIES[name];
        const afterRoot = css.slice(css.indexOf('}', css.indexOf(':root')) + 1);

        // Comments explain why a colour was chosen and name values while doing
        // it, which is not the same as declaring one.
        const rules = afterRoot.replace(/\/\*[\s\S]*?\*\//g, '');

        const literals = [
            ...rules.matchAll(/#[0-9a-fA-F]{3,8}\b/g),
            ...rules.matchAll(/\b(?:rgba?|hsla?)\s*\(/g),
        ].map((match) => match[0]);

        expect(literals).toEqual([]);
    });
});

describe('the front page images resolve', () => {

    /**
     * The defect #140 opened on. Every relative `src` on the built front page
     * has to exist under the built site, because that is where a browser
     * resolves it from -- not from the repository root, which is where the
     * README is written for.
     */
    test('every relative src on the built front page exists in the output', () => {
        const sources = [...builtIndex.matchAll(/<img[^>]+src="([^"]+)"/g)]
            .map((match) => match[1])
            .filter((src) => !/^(?:https?:)?\/\//.test(src))
            .filter((src) => !src.startsWith('data:'));

        expect(sources.length).toBeGreaterThan(0);

        const missing = sources.filter((src) => !fs.existsSync(path.join(BUILT, src)));

        expect(missing).toEqual([]);
    });

    test('the logo and the mark are among them', () => {
        expect(builtIndex).toContain('frontend/shared/assets/images/marp-logo.png');
        expect(builtIndex).toContain('frontend/shared/assets/images/marp-mark.png');
    });

    /**
     * R2. The fix must not have been to edit the README, which is read on GitHub
     * far more often than the generated site is read at all.
     */
    test('the README still references its images from the repository root', () => {
        const readme = read(ROOT, 'README.md');

        expect(readme).toContain('src="frontend/shared/assets/images/marp-logo.png"');
        expect(fs.existsSync(path.join(ROOT, 'frontend', 'shared', 'assets', 'images', 'marp-logo.png'))).toBe(true);
    });
});

describe('the built site wears the theme', () => {

    test('the stylesheet is linked from the head, not appended to the body', () => {
        const head = builtIndex.slice(0, builtIndex.indexOf('</head>'));

        expect(head).toContain('styles/marp-docs.css');
    });

    test('the stylesheet was copied into the output', () => {
        expect(fs.existsSync(path.join(BUILT, 'styles', 'marp-docs.css'))).toBe(true);
    });

    test('every page carries the bar, not just the front one', () => {
        const pages = fs.readdirSync(BUILT).filter((name) => name.endsWith('.html'));

        expect(pages.length).toBeGreaterThan(100);

        const without = pages
            .filter((name) => !fs.readFileSync(path.join(BUILT, name), 'utf8').includes('class="marp-bar"'))
            .slice(0, 5);

        expect(without).toEqual([]);
    });

    /**
     * Six hand-written markdown documents live inside the generated directory,
     * and jsdoc will never put them back. They survive a normal build because
     * jsdoc does not clean its output -- and a `rm -rf docs/developer` before a
     * rebuild takes all six, silently, which is exactly what the clean-rebuild
     * step in `.marp/verification.md` asks somebody to do. It happened once
     * here and was caught by reading a deletion list.
     */
    test('the hand-written documents inside the generated directory survive', () => {
        const written = [
            'csharp-host-integration.md',
            'media-source-architecture.md',
            'scheduler-current-algorithm.md',
            'video-player-library-handoff.md',
            'webview2-integration-plan.md',
            'webview2-test-setup-instructions.md',
        ];

        const lost = written.filter((name) => !fs.existsSync(path.join(BUILT, name)));

        expect(lost).toEqual([]);
    });

    /**
     * The fonts and the `@font-face` rules that pointed at them were removed
     * together. Either one without the other is a broken site or 1.2 MB of dead
     * weight, so they are asserted together.
     */
    test('no webfont is shipped and none is declared', () => {
        expect(fs.existsSync(path.join(BUILT, 'fonts'))).toBe(false);
        // The rule, not the word: the comment left in its place explains the
        // removal and names what it removed.
        expect(read(THEME, 'static', 'styles', 'jsdoc.css')).not.toMatch(/@font-face\s*\{/);
    });
});

describe('both surfaces carry the same bar', () => {

    /**
     * R10. Two copies of ten lines of markup, because swagger-ui-express renders
     * from a template string with no seam for HTML. This is the half that will
     * be forgotten.
     */
    test('each links to the platform and to the other surface', () => {
        expect(layoutTmpl).toContain('href="/"');
        expect(layoutTmpl).toContain('href="/api-docs"');

        expect(swaggerChrome).toContain("href=\"/\"");
        expect(swaggerChrome).toContain('href="/developer-docs"');
    });

    test('each says which surface it is', () => {
        expect(layoutTmpl).toContain('Developer documentation');
        expect(swaggerChrome).toContain('API reference');
    });

    test('each uses the compact logo, the treatment the applications use', () => {
        expect(layoutTmpl).toContain('marp-logo-compact.png');
        expect(swaggerChrome).toContain('marp-logo-compact.png');
    });

    /**
     * docdash's stylesheet assumes there is exactly one `<nav>` and gives it the
     * whole fixed sidebar. A second one in the bar inherited all of it and
     * painted a 250px panel over the real navigation.
     */
    test('the bar links are not a second nav element', () => {
        expect(layoutTmpl).not.toMatch(/<nav class="marp-bar__links"/);
        expect(swaggerChrome).not.toContain('<nav class="marp-bar__links"');
    });

    test('app.js hands the bar and the theme to Swagger', () => {
        const appJs = read(ROOT, 'app.js');

        expect(appJs).toContain("'swagger-chrome.js'");
        expect(appJs).toContain('customJsStr');
        expect(appJs).toContain("'swagger.css'");
    });
});

describe('the fork stayed a diff', () => {

    /**
     * R7. Everything except the two files MARP deliberately changed is supposed
     * to be byte-identical to docdash, so `diff -r` remains the whole upgrade
     * procedure. A failure here is not necessarily a defect -- a docdash bump
     * will trip it -- but it must never happen silently.
     */
    const CHANGED = ['tmpl/layout.tmpl', 'static/styles/jsdoc.css'];

    /** MARP's own, with no upstream counterpart. */
    const ADDED = ['publish.js', 'README.md', 'static/styles/marp-docs.css'];

    test('nothing in the fork is missing from upstream except what MARP added', () => {
        const unexpected = filesUnder(THEME)
            .filter((file) => !ADDED.includes(file))
            .filter((file) => !fs.existsSync(path.join(UPSTREAM, file)));

        expect(unexpected).toEqual([]);
    });

    test('every unchanged file still matches docdash', () => {
        const differing = filesUnder(THEME)
            .filter((file) => !ADDED.includes(file))
            .filter((file) => !CHANGED.includes(file))
            .filter((file) => fs.existsSync(path.join(UPSTREAM, file)))
            .filter((file) => text(path.join(THEME, file)) !== text(path.join(UPSTREAM, file)));

        expect(differing).toEqual([]);
    });

    /**
     * The one change to docdash's stylesheet is a truncation, so everything
     * before the cut has to still match. This catches a rule edited in place,
     * which is the change that would make the fork expensive.
     */
    test('the forked jsdoc.css is upstream truncated, not upstream edited', () => {
        const mine = read(THEME, 'static', 'styles', 'jsdoc.css');
        const theirs = read(UPSTREAM, 'static', 'styles', 'jsdoc.css');

        const kept = normalise(mine.slice(0, mine.indexOf('/* The four @font-face blocks')));

        expect(kept.length).toBeGreaterThan(1000);
        expect(normalise(theirs).startsWith(kept)).toBe(true);
    });

    test('publish.js forks no logic', () => {
        const publish = read(THEME, 'publish.js');

        expect(publish).toContain("require('docdash/publish.js')");
        expect(publish.replace(/\/\*\*[\s\S]*?\*\//, '').trim().split('\n').length).toBe(1);
    });

    test('the build is wired to the fork and to the mirroring step', () => {
        const config = JSON.parse(read(ROOT, 'jsdoc.config.json'));
        const pkg = JSON.parse(read(ROOT, 'package.json'));

        expect(config.opts.template).toBe('docs/developer-theme');
        expect(config.opts.readme).toBe('README.md');
        expect(pkg.scripts['docs:dev:build']).toContain('build-developer-docs.js');
        expect(pkg.scripts['docs:build']).toContain('docs:dev:build');
    });
});
